[package]
name = "yee-util"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"


[dependencies]
parking_lot = {version = "=0.7.1", features = ["deadlock_detection"]}
fnv = "1.0.3"

