[package]
name = "yee"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "yee"
path = "src/main.rs"

[dependencies]

[build-dependencies]
vergen = "3"

[workspace]
