[package]
name = "yee-consensus-pow"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
log = "0.4"
parity-codec = "3.5"
parking_lot = "0.7.1"
tokio = "0.1"
pow_primitives = { package = "yee-consensus-pow-primitives", path = "primitives" }
yee-srml-pow = { path = "../../../srml/yee-pow" }
client = { package = "substrate-client", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0"}
consensus_common = { package = "substrate-consensus-common", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
inherents = { package = "substrate-inherents", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
srml-timestamp = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
serde = { version = "1.0", optional = true, features = ["derive"] }
merkle_light = { git = "https://github.com/yeeco/merkle_light.git", branch = "yee" }
yee-sharding = { package = "yee-sharding", path = "../../sharding" }
yee-sharding-primitives = { package = "yee-sharding-primitives", path = "../../sharding/primitives" }

[dev-dependencies]
hex-literal = "0.2"
hex = "0.3.1"
yee-runtime = { package = "yee-runtime", path = "../../../runtime" }

[features]
default = ["std"]
std = [
	"serde",
]
