[package]
name = "crfg-primitives"
version = "0.4.0"
authors = ["YeeCo contact@yeefoundation.com"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", git = "https://github.com/yeeco/substrate.git", default-features = false , rev = "e015c881080fbef2733413eb0fb5864b9c272797"}
substrate-primitives = { git = "https://github.com/yeeco/substrate.git", default-features = false , rev = "e015c881080fbef2733413eb0fb5864b9c272797" }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }
sr-primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", default-features = false , rev = "e015c881080fbef2733413eb0fb5864b9c272797" }
rstd = { package = "sr-std", git = "https://github.com/yeeco/substrate.git", default_features = false, rev = "e015c881080fbef2733413eb0fb5864b9c272797" }

[features]
default = ["std"]
std = [
	"substrate-primitives/std",
	"client/std",
	"parity-codec/std",
	"sr-primitives/std",
	"rstd/std",
]
