[package]
name = "yee-mining"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"


[dependencies]
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
faketime = "0.2.0"
rand = "0.6"
byteorder = "1.3.1"
serde = "1.0"
serde_derive = "1.0"
crossbeam-channel = "0.3"
fnv = "1.0.3"
serde_json = "1.0"
hyper = "0.12"
failure = "0.1.5"
yee-stop-handler = { package = "yee-stop-handler", path = "util/stop-handler" }
yee-jsonrpc-types = { package = "yee-jsonrpc-types", path = "util/jsonrpc-types" }
yee-lru-cache = { package = "yee-lru-cache", path = "util/lru-cache" }
yee-util = { package = "yee-util", path = "util" }
primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", rev = "890461d48ad04070def58fdda3c23876e9b5339d" }
tokio = "0.1.7"
exit-future = "0.1"
futures = "0.1"
log = "0.4"
uuid = { version = "0.7", features = ["serde", "v4"] }
parity-codec = "3.2"
chrono = "0.4"
rust-crypto = "0.2.36"
yee-primitives = { package = "yee-primitives", path = "../../core/primitives" }
merkle_light = { git = "https://github.com/yeeco/merkle_light.git", rev = "fd8bd7352681126fe4cf2d7f225de96d645bd1e1" }
yee-consensus-pow = { package = "yee-consensus-pow", path = "../../core/consensus/pow" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", rev = "890461d48ad04070def58fdda3c23876e9b5339d" }
yee-rpc = { package = "yee-rpc", path = "../../rpc" }
yee-serde-hex = { package = "yee-serde-hex", path = "../../rpc/serde-hex" }
