[package]
name = "yee-switch"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
clap = "~2.32"
structopt = "0.2"
log = "0.4"
substrate-cli = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }



