[package]
name = "foreign-chain-interface"
version = "0.4.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-service = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
