[package]
name = "yee-merkle"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
[dependencies]
serde = "1.0"
serde_derive = "1.0"
primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "v1.0" }
blake2-rfc = "0.2.18"
parity-codec = "3.2"
rust-crypto = "0.2.36"

