[package]
name = "yee-foreign-network"
version = "0.4.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
network-libp2p = { package = "yee-foreign-network-libp2p", path = "../network-libp2p" }
