[package]
name = "yee-stop-handler"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parking_lot = "=0.7.1"
crossbeam-channel = "0.3"
futures = "0.1"
